- name: configure frontend component
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx on frontend server
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx version
    ansible builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx module
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html empty directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend code
    ansible.buitin.get_url: 
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip  

  - name: unzip frontend code
    ansible.builtin.unarchieve:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove default nginxconf file
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent  

  - name: copy roboshop nginxconf file
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted




